#!/bin/bash
# Quick Start Guide - Test Your Chat Feature

echo "🚀 Chat Feature Setup Guide"
echo "============================"
echo ""

# Step 1: Environment Setup
echo "Step 1: Create .env.local"
echo "------------------------"
echo "Create a file named '.env.local' in your project root with:"
echo ""
echo "TELEGRAM_BOT_TOKEN=your_bot_token_here"
echo "TELEGRAM_CHAT_ID=your_chat_id_here"
echo ""
echo "⚠️  Replace with actual values from:"
echo "  - @BotFather on Telegram for bot token"
echo "  - @userinfobot for your chat ID"
echo ""

# Step 2: Install Dependencies
echo "Step 2: Ensure Dependencies Installed"
echo "------------------------------------"
echo "Run: npm install"
echo ""
echo "Make sure you have:"
echo "  - react: installed"
echo "  - react-icons: installed"
echo "  - typescript: installed"
echo "  - @vercel/node: installed (for serverless functions)"
echo ""

# Step 3: Local Testing
echo "Step 3: Test Locally with Vercel CLI"
echo "-----------------------------------"
echo "1. Install Vercel CLI:"
echo "   npm install -g vercel"
echo ""
echo "2. Run locally:"
echo "   vercel dev"
echo ""
echo "3. Open browser:"
echo "   http://localhost:3000"
echo ""
echo "4. Test the chat:"
echo "   - Click 'Chat with me!' button"
echo "   - Type a message"
echo "   - Click Send or press Enter"
echo "   - Check your Telegram for the message"
echo ""

# Step 4: Telegram Setup
echo "Step 4: Telegram Bot Setup"
echo "------------------------"
echo "1. Open Telegram and search for @BotFather"
echo "2. Send /newbot"
echo "3. Name your bot (e.g., 'Portfolio Bot')"
echo "4. Create username (e.g., 'portfolio_portfolio_bot')"
echo "5. Copy the token → Set as TELEGRAM_BOT_TOKEN"
echo ""
echo "6. Search for @userinfobot"
echo "7. Copy your User ID → Set as TELEGRAM_CHAT_ID"
echo ""

# Step 5: Test Reply Flow
echo "Step 5: Test Reply Flow"
echo "---------------------"
echo "1. User sends message from chat (test locally or in prod)"
echo ""
echo "2. You receive in Telegram:"
echo "   [session: session_xxx_xxx]"
echo "   User's message here"
echo ""
echo "3. You reply in Telegram with session ID:"
echo "   [session: session_xxx_xxx]"
echo "   Your response here"
echo ""
echo "4. Browser polls every 2 seconds and shows reply"
echo "   Message appears under 'you' sender type"
echo ""

# Step 6: Production Deploy
echo "Step 6: Deploy to Production"
echo "---------------------------"
echo "1. Push changes to GitHub"
echo "2. Vercel auto-deploys (if connected)"
echo "   OR manually run: vercel --prod"
echo ""
echo "3. Set environment variables in Vercel Dashboard:"
echo "   - Go to Settings → Environment Variables"
echo "   - Add TELEGRAM_BOT_TOKEN"
echo "   - Add TELEGRAM_CHAT_ID"
echo ""
echo "4. Test in production URL"
echo ""

# Step 7: Features Verification
echo "Step 7: Verify Features"
echo "---------------------"
echo "✅ sessionId generated on first visit (check localStorage)"
echo "✅ Messages saved to localStorage (refresh and see messages)"
echo "✅ Rate limiting active (send 2 messages quickly → see alert)"
echo "✅ Message appears immediately after send"
echo "✅ Message format correct in Telegram: [session: xxx]\\nmessage"
echo "✅ Reply appears in browser within 2-4 seconds"
echo "✅ Dark mode works in chat"
echo "✅ Mobile: chat is full screen"
echo "✅ Desktop: chat is 500px sidebar"
echo ""

# File Structure
echo "Step 8: File Structure"
echo "--------------------"
echo "Your chat feature files:"
echo ""
echo "src/components/"
echo "  └─ Chat.tsx (updated with localStorage & API)"
echo ""
echo "src/"
echo "  └─ App.tsx (updated to use new Chat component)"
echo ""
echo "api/"
echo "  ├─ send-message.ts (sends to Telegram)"
echo "  ├─ get-replies.ts (polls for replies)"
echo "  └─ get-replies-redis.ts (production upgrade - optional)"
echo ""
echo "Documentation:"
echo "  ├─ TELEGRAM_SETUP.md (detailed setup guide)"
echo "  ├─ CHAT_FEATURE_SUMMARY.md (complete reference)"
echo "  ├─ TELEGRAM_REPLY_FORMAT.md (reply format guide)"
echo "  └─ QUICK_START.sh (this file)"
echo ""

# Troubleshooting
echo "Step 9: If Something's Wrong"
echo "----------------------------"
echo ""
echo "Messages not sending?"
echo "  □ Check .env.local has correct TELEGRAM_BOT_TOKEN"
echo "  □ Check .env.local has correct TELEGRAM_CHAT_ID"
echo "  □ Check bot exists in Telegram (@BotFather)"
echo "  □ Check network tab in DevTools for API errors"
echo ""
echo "Replies not appearing?"
echo "  □ Verify reply includes [session: xxx] format"
echo "  □ Check browser console for fetch errors"
echo "  □ Ensure polling is running (check Network tab)"
echo ""
echo "localStorage not working?"
echo "  □ Check DevTools → Application → Storage → localStorage"
echo "  □ Look for 'chat_messages' and 'chat_sessionId'"
echo "  □ If missing, clear site data and refresh"
echo ""

# Success Message
echo ""
echo "=========================================="
echo "✨ Setup Complete! 🎉"
echo "=========================================="
echo ""
echo "Next: Set up environment variables and run 'vercel dev'"
echo "Questions? See TELEGRAM_SETUP.md for detailed instructions"
echo ""
